### ISSUE TITLE
How do i compile it on Windows?

### ISSUE THREAD

**Issue by Gabitzuu** [4x11/SAMP-Android#5]
C:\Users\Gabitzuu\Desktop\libsamp>ndk-build NDK_APPLICATION_MK=./Application.mk
Android NDK: android-14 is unsupported. Using minimum supported version android-16.
Android NDK: There is no Android.mk under "C:\Users\Gabitzuu\Desktop\libsamp"/jni
Android NDK: If this is intentional  please define APP_BUILD_SCRIPT to point
Android NDK: to a valid NDK build script.
C:/ndk/build//../build/core/add-application.mk:103: *** Android NDK: Aborting...    .  Stop.

how do i fix this?

**Comment by Kronka** [comment]
Minimal android sdk 16, not 14...

**Comment by soly-olf** [comment]
You can just use older ndk version, for example 14b, or change sdk version

**Comment by 4x11** [comment]
change in Application.mk
`APP_PLATFORM := android-14`
to
`APP_PLATFORM := android-16`

**Comment by Gabitzuu** [comment]
I changed the APP_PLATFORM to android-16 but i'm still getting this error:

C:\Users\Gabitzuu\Desktop\libsamp>ndk-build NDK_APPLICATION_MK=./Application.mk
Android NDK: There is no Android.mk under C:\Users\Gabitzuu\Desktop\libsamp/jni
Android NDK: If this is intentional  please define APP_BUILD_SCRIPT to point
Android NDK: to a valid NDK build script.
C:/ndk/build//../build/core/add-application.mk:103: *** Android NDK: Aborting...    .  Stop.

**Comment by soly-olf** [comment]
Set a valid path .mk files on NDK_APPLICATION_MK and APP_BUILD_SCRIPT

**Comment by Gabitzuu** [comment]
I fixed it putting them in the damn command, but i'm getting the error you can see in the top post now, and i can't fix it...

**Comment by soly-olf** [comment]
compile with 
`APP_STL=c++_shared`

**Comment by Gabitzuu** [comment]
So from where can i get Imgui cuz it won't compile it without imgui

**Comment by soly-olf** [comment]
[https://github.com/ocornut/imgui](imgui)

**Comment by Gabitzuu** [comment]
```
./game/hooks.cpp:71:12: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                        st[1] = (uint32_t)fopen(path, "rb");
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:80:12: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                        st[1] = (uint32_t)fopen(path, "rb");
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:89:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:98:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "r");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:107:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:134:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:143:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:152:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:161:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:170:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:179:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:188:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "r");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:197:11: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:371:42: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
        byteCurDriver = FindPlayerNumFromPedPtr((uint32_t)pVehicle->pDriver);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./game/hooks.cpp:654:47: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
                        if (GamePool_FindPlayerPed()->pVehicle == (uint32_t)pVehicle) {
                                                                  ^~~~~~~~~~~~~~~~~~
./game/hooks.cpp:780:32: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
        *(uint32_t*)&pickup_code[8] = (uint32_t)PickupPickUp_hook;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
16 errors generated.
make: *** [C:\Users\Gabitzuu\Desktop\libsamp/obj/local/arm64-v8a/objs/samp/game/hooks.o] Error 1```

the fuck is happening i never get this errors when compiling something with ndk/make

**Comment by soly-olf** [comment]
u are really?
NDK_APPLICATION_MK=C:\Users\Gabitzuu\Desktop\libsamp\Application.mk

**Comment by Gabitzuu** [comment]
``ndk-build NDK_APPLICATION_MK=Android.mk APP_PLATFORM=android-16 APP_BUILD_SCRIPT=./Android.mk APP_STL=c++_shared NDK_PROJECT_PATH=C:\Users\Gabitzuu\Desktop\libsamp`` that's the command i run...

**Comment by soly-olf** [comment]
`ndk-build NDK_APPLICATION_MK=C:\Users\Gabitzuu\Desktop\libsamp\Android.mk APP_PLATFORM=android-16 APP_BUILD_SCRIPT=C:\Users\Gabitzuu\Desktop\libsamp\Android.mk APP_STL=c++_static NDK_PROJECT_PATH=C:\Users\Gabitzuu\Desktop\libsamp`

**Comment by Gabitzuu** [comment]
still getting this error:
```
C:\Users\Gabitzuu\Desktop\libsamp>ndk-build NDK_APPLICATION_MK=C:\Users\Gabitzuu\Desktop\libsamp\Android.mk APP_PLATFORM=android-16 APP_BUILD_SCRIPT=C:\Users\Gabitzuu\Desktop\libsamp\Android.mk APP_STL=c++_static NDK_PROJECT_PATH=C:\Users\Gabitzuu\Desktop\libsamp
[arm64-v8a] Compile++      : samp <= hooks.cpp
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:71:12: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                        st[1] = (uint32_t)fopen(path, "rb");
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:80:12: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                        st[1] = (uint32_t)fopen(path, "rb");
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:89:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:98:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "r");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:107:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:134:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:143:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:152:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:161:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:170:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:179:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:188:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "r");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:197:11: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                st[1] = (uint32_t)fopen(path, "rb");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:371:42: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
        byteCurDriver = FindPlayerNumFromPedPtr((uint32_t)pVehicle->pDriver);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:654:47: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
                        if (GamePool_FindPlayerPed()->pVehicle == (uint32_t)pVehicle) {
                                                                  ^~~~~~~~~~~~~~~~~~
C:/Users/Gabitzuu/Desktop/libsamp/game/hooks.cpp:780:32: error: cast from pointer to smaller type 'uint32_t'
      (aka 'unsigned int') loses information
        *(uint32_t*)&pickup_code[8] = (uint32_t)PickupPickUp_hook;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
16 errors generated.
make: *** [C:\Users\Gabitzuu\Desktop\libsamp/obj/local/arm64-v8a/objs/samp/game/hooks.o] Error 1
```

**Comment by soly-olf** [comment]
`ndk-build NDK_PROJECT_PATH=C:\Users\Gabitzuu\Desktop\libsamp APP_BUILD_SCRIPT=C:\Users\Gabitzuu\Desktop\libsamp\Android.mk NDK_APPLICATION_MK=C:\Users\Gabitzuu\Desktop\libsamp\Application.mk APP_STL=c++_static`

successful compile

**Comment by Gabitzuu** [comment]
as i see this uses a old imgur version because it doesn't work with latest
```
[armeabi-v7a] Compile++ thumb: samp <= renderware_imgui.cpp
C:/Users/Gabitzuu/Desktop/libsamp/gui/renderware_imgui.cpp:166:9: error: no member named 'Shutdown' in namespace 'ImGui'
        ImGui::Shutdown();
        ~~~~~~~^
1 error generated.
make: *** [C:\Users\Gabitzuu\Desktop\libsamp/obj/local/armeabi-v7a/objs/samp/gui/renderware_imgui.o] Error 1
```

**Comment by soly-olf** [comment]
yes

**Comment by Gabitzuu** [comment]
can you give me your version of imgui please?

**Comment by soly-olf** [comment]
try 1.50-1.52

**Comment by Gabitzuu** [comment]
```
C:\Users\Gabitzuu\Desktop\libsamp>ndk-build NDK_PROJECT_PATH=C:\Users\Gabitzuu\Desktop\libsamp APP_BUILD_SCRIPT=C:\Users\Gabitzuu\Desktop\libsamp\Android.mk NDK_APPLICATION_MK=C:\Users\Gabitzuu\Desktop\libsamp\Application.mk APP_STL=c++_static
[armeabi-v7a] SharedLibrary  : libsamp.so
C:/Users/Gabitzuu/Desktop/libsamp/imgui-src/imgui.h:1503: error: undefined reference to 'ImGui::SetScrollHereY(float)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [C:\Users\Gabitzuu\Desktop\libsamp/obj/local/armeabi-v7a/libsamp.so] Error 1```
i tried with 1.50, 1.51, 1.52

**Comment by soly-olf** [comment]
i use v1.53 :D

**Comment by Gabitzuu** [comment]
Hmm still getting this error with v1.53 the fuck

**Comment by soly-olf** [comment]
are you sure?

**Comment by Gabitzuu** [comment]
yes

**Comment by Gabitzuu** [comment]
Oh it works now, thanks for helping me <3

**Comment by SteelSa** [comment]
I get this error when building, help me figure it out
![C_F6jV9IrSU](https://user-images.githubusercontent.com/46651099/56462919-da1b9200-63d3-11e9-858b-ce620705daae.jpg)

**Comment by aktah** [comment]
same here !!

[armeabi-v7a] Compile++ thumb: samp <= renderware_imgui.cpp
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:166:9: error: no member named 'Shutdown' in namespace 'ImGui'
        ImGui::Shutdown();
        ~~~~~~~^
1 error generated.
make: *** [D:\repositity\SAMP-Android/obj/local/armeabi-v7a/objs/samp/gui/renderware_imgui.o] Error 1

**Comment by aktah** [comment]
On imgui v.1.53

[armeabi-v7a] Compile++ thumb: samp <= chatwindow.cpp
[armeabi-v7a] Compile++ thumb: samp <= hooks.cpp
[armeabi-v7a] Compile++ thumb: samp <= renderware_imgui.cpp
[armeabi-v7a] SharedLibrary  : libsamp.so
D:/repositity/SAMP-Android/chatwindow.cpp:25: error: undefined reference to 'ImGui::Begin(char const*, bool*, int)'
D:/repositity/SAMP-Android/chatwindow.cpp:26: error: undefined reference to 'ImGui::SetWindowPos(ImVec2 const&, int)'
D:/repositity/SAMP-Android/chatwindow.cpp:27: error: undefined reference to 'ImGui::SetWindowSize(ImVec2 const&, int)'
D:/repositity/SAMP-Android/chatwindow.cpp:37: error: undefined reference to 'ImGui::TextColored(ImVec4 const&, char const*, ...)'
D:/repositity/SAMP-Android/chatwindow.cpp:38: error: undefined reference to 'ImGui::SameLine(float, float)'
D:/repositity/SAMP-Android/imgui53/imgui.h:1277: error: undefined reference to 'ImGui::PushStyleColor(int, ImVec4 const&)'
D:/repositity/SAMP-Android/imgui53/imgui.h:0: error: undefined reference to 'ImGui::PopStyleColor(int)'
D:/repositity/SAMP-Android/chatwindow.cpp:56: error: undefined reference to 'ImGui::SetScrollHere(float)'
D:/repositity/SAMP-Android/chatwindow.cpp:57: error: undefined reference to 'ImGui::End()'
D:/repositity/SAMP-Android/game/hooks.cpp:745: error: undefined reference to 'ImGui::Render()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:91: error: undefined reference to 'ImGui::TextUnformatted(char const*, char const*)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:61: error: undefined reference to 'ImGui::TextUnformatted(char const*, char const*)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:62: error: undefined reference to 'ImGui::SameLine(float, float)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:75: error: undefined reference to 'ImGui::PopStyleColor(int)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:82: error: undefined reference to 'ImGui::PushStyleColor(int, ImVec4 const&)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:100: error: undefined reference to 'ImGui::TextUnformatted(char const*, char const*)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:104: error: undefined reference to 'ImGui::NewLine()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:109: error: undefined reference to 'ImGui::PopStyleColor(int)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:157: error: undefined reference to 'ImGui::GetIO()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:187: error: undefined reference to 'ImGui::GetIO()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:281: error: undefined reference to 'ImGui::GetIO()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:166: error: undefined reference to 'ImGui::Shutdown()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:281: error: undefined reference to 'ImGui::GetIO()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:182: error: undefined reference to 'ImGui::NewFrame()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:253: error: undefined reference to 'ImFontAtlas::GetGlyphRangesCyrillic()'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:253: error: undefined reference to 'ImFontAtlas::AddFontFromFileTTF(char const*, float, ImFontConfig const*, unsigned short const*)'
D:/repositity/SAMP-Android/gui/renderware_imgui.cpp:254: error: undefined reference to 'ImFontAtlas::GetTexDataAsRGBA32(unsigned char**, int*, int*, int*)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [D:\repositity\SAMP-Android/obj/local/armeabi-v7a/libsamp.so] Error 1
